### ISSUE TITLE
Add a hover effect

### ISSUE THREAD

**Issue by Bashamega** [Yefee8/uiassistant#1]
Hello:)
I would love to contribute by making a hover effect when you hover

**Comment by Yefee8** [comment]
If you open a pr about it, I'll check it. Thanks!

**Comment by Bashamega** [comment]
> If you open a pr about it, I'll check it. Thanks!

Your welcome

**Comment by Bashamega** [comment]
Would you mind creating a good file structure, rather than all the code in one big file?

**Comment by Yefee8** [comment]
It's html so I don't think we can. but in CSS side yup you can.
